### ISSUE TITLE
gal_nextmap_change support for amx_votemap

### ISSUE THREAD

**Issue by mo0nsniper** [evandrocoan/MultiModServer#47]
There is a problem with the current implementation.

If I set `amx_cvar amx_nextmap fy_snow` the `nextmap` command reports still `[not voted on]`
And after the time is up and the last round finishes the map doesn't change to anything. `timelimit` reports `No time limit`

**Comment by evandrocoan** [comment]
Does this is the same as this other issue?

1. https://github.com/evandrocoan/Galileo/issues/22 gal_nextmap_change support for amx_votemap

**Comment by mo0nsniper** [comment]
It's related to that issue, but it's not the same.
The problem for me was that I am using reamxmodx for rehlds engine, and the plugin didn't compile on reamxmodx so I was using the older version of the plugin.

Now I tried compiling the newest version of galileo with the reamxmodx compiler. It compiles now but the server crashes when starting.

I'll try to compile galileo with the original amx 1.8.3 compiler and see it it works.

**Comment by evandrocoan** [comment]
What is the crash reason on the reamxmodx? Something on the logs? Do you use the `-condebug` command line?

**Comment by mo0nsniper** [comment]
This is the error that I get when compiling galileo v3.2.6-379 with reamxmodx compiler:
Compiling galileo.sma
AMX Mod X Compiler 1.8.3-dev+5067
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2013 AMX Mod X Team

galileo.sma(12986) : error 088: number of arguments does not match definition
galileo.sma(12992) : error 088: number of arguments does not match definition

2 Errors.
Could not locate output file compiled/galileo.amx (compile failed).

With the amx 1.8,3 compiler it compiles but again the server crashes.
I have put debug after galileo.amxx in plugins.ini but I have nothing in the console or in debug.log.
Here is [_galileo.log](http://pastebin.com/Zf9WW3Wd)

Where should I put `-condebug` ?

**Comment by evandrocoan** [comment]
> Where should I put `-condebug` ?

If there are any on the './addons/amxmodx/logs' and './logs' folders, see what you get with the '-condebug' option. If it is enabled, the 'qconsole.log' file on the 'Half-File' folder.
If the file 'qconsole.log' does not exist, you need to enable the condebug adding '-condebug' to the server command line options. 

Example:
./hlds_run -console -game cstrike -pingboost 2 +log on -autoupdate **-condebug** -noaff **-debug** **-allowdebug** -secure +map de_dust2 +maxplayers 32 +port 27015

> With the amx 1.8,3 compiler it compiles but again the server crashes.

I created a new version, `v3.2.6-381`, it it should be fixed. If not, send me the new `_galileo.log` file.

1. First try to compile with the reamxmodx,
1. Then if not work, use the amxx 182,
1. And if not work, the amx 183.

Also, where I can download the reamxmodx compiler?

**Comment by mo0nsniper** [comment]
The original forum thread for reamxmodx is [here](http://www.dedicated-server.ru/vbb/showthread.php?t=27127).
The forum is in russian and if you can't make a user to download it you can download the version 6 that I'm using from [here](https://miez.dattodrive.com/index.php/s/qfPRmUdIE41T0Mh/download) (the latest version is 7 but I haven't updated yet)

**Comment by evandrocoan** [comment]
Thanks for link.

**Comment by mo0nsniper** [comment]
Updated to `"gal_version" "v3.2.6-394"`
Now compiling works with the reamxmodx compiler and the server doesn't crash anymore.

But the behavior is the same. 
Tried with the reamxmodx compiler, amx 1.8.2 and amx 1.8.3 but the [not voted on] value stays the same

What should I do to further debug this issue?

**Comment by evandrocoan** [comment]
Follow the debug instructions on: 

1. https://forums.alliedmods.net/showthread.php?t=273019#Support

Basically:

1. Enabled the debug
1. Open you server
1. To do the actions you want to do by are not working.

It will record what the plugin was doing. Then if you send me the log, I should know why it was not doing it.

> [*]You can enable the DEBUG_LEVEL on 16, instead of 0, as default. [URL="https://forums.alliedmods.net/showthread.php?t=273019#Development"]See here how[/URL] to do it. After that,
to install the plugin, let your server run until the problem you are experiencing happens and after
that send me by PM or post here log file '[COLOR="Blue"]_galileo.log[/COLOR]'. It will be at the folder '[COLOR="blue"]addons/amxmodx/logs[/COLOR]'.

Also, the version you are using has new built-in features which replace the `amx_votemap`. So, instead of use `amx_votemap map1 map2`, use `gal_votemap map1 map2`. Or even, choose the maps by the `say galmenu`

>  [*] Command '[COLOR="Blue"][B]say galmenu [page_number][/B][/COLOR]', (admin MAP level required) to choose from the loaded server
     maps, the maps to create a map voting by a menu, as the one with the `gal_votemap` command. Consider here the
     nomination file list as maps source to build up the menu. If specified the `page_number` argument, the menu
     will be opened a the specified page. Example: `say galmenu 50` will open the menu right on the page 50.
     If the argument `page_number` is omitted, the menu will open at the first page, or the last page
     you opened it.


___

>  [*] Command '[COLOR="Blue"][B]gal_votmemap[/B][/COLOR]', to receive a list of maps and will to perform a map voting
     as if it was an automatic end of map voting. It has the following optional arguments:


> [LIST]
[*]If the "[COLOR="blue"][B]-nointro[/B][/COLOR]" argument is supplied, the countdown "7", "6", "5", "4", "3", "2", "1"
will be skipped and the voting will start immediately as you send the command.


> [*]If the "[COLOR="blue"][B]-norunoff[/B][/COLOR]" argument is supplied, the runoff vote will be disabled
for this voting, if it is not already disabled by the cvar `gal_runoff_enabled`.


> [*]If the "[COLOR="blue"][B]-noextension[/B][/COLOR]" argument is supplied, the map extension will be disabled
for this voting, if it is not already disabled by the cvar `amx_extendmap_step`.


> [*]If the "[COLOR="blue"][B]-loadnominations[/B][/COLOR]" argument is supplied, the map nominations will be loaded
for this voting, if they are enabled by the cvar `gal_nom_playerallowance`.
[/LIST]

> [B]Usage examples:[/B]
[code]
These are the `gal_votemap` command usage examples:

> gal_votemap map1 map2 map3 map4 ... map9
gal_votemap map1 map2 map3 map4 ... map9 -nointro -noextension -norunoff
gal_votemap map1 map2 map3 map4 ... map9 -nointro -noextension
gal_votemap map1 map2 map3
gal_votemap map1 map2 -nointro -noextension
gal_votemap map1 map2 -nointro
gal_votemap map1 map2 -loadnominations
gal_votemap map1 map2
    [/code]

**Comment by evandrocoan** [comment]
Closing this as the problem the crash problem is solved. Continuing it on the original issue:

1. https://github.com/evandrocoan/Galileo/issues/22 gal_nextmap_change support for amx_votemap
