### ISSUE TITLE
Compiling error with this plugin using git-5132

### ISSUE THREAD

**Issue by evandrocoan** [evandrocoan/MultiModServer#76]
> [QUOTE=Ricky;2540976]I am getting this compiling error with this plugin using git-5132. Need help.

> Invalid function or declaration. Tag mismatch on line 11123.

> Code:

> [CODE]return strcmp( map1, map2, 1 );[/CODE][/QUOTE]

https://forums.alliedmods.net/showpost.php?p=2540976&postcount=826

**Comment by regener** [comment]
This is caused by the change in string.inc:
Before it was an integer:
`native strcmp(const string1[], const string2[], ignorecase=0);`
Now it is a boolean:
`native strcmp(const string1[], const string2[], bool:ignorecase = false);`

So you have to simply change the "1" to "true":
`		return strcmp( map1, map2, true );`
Yet both older and new version compiles successfully, but I don't know what value will the older compilers read from a word instead a number.
